<html>
<head>
<style>
.labelVisible{margin:13px 0px 0px 25%;}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gestionar validación de negocio</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<script language="javascript" type="text/javascript">importarCSS(window.parent.UCID.portal.perfil.dirCss);</script>
</head>

<body>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/gestvalidacionnegocio/gestvalidacionnegocio.js"></script>
</body>
</html>