<html>
<head>
    <title>Gestionar Estructura</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/imporcss.js"></script>
    <link href="<?php echo $this->dir_ext_ccs; ?>../default/css/ext-all.css" rel="stylesheet" type="text/css"
          media="screen"/>
</head>
<body>
<div id="element"></div>
<link href="../../css/css/org.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->dir_extjs; ?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs; ?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/estructura/ucid-win-iframe.js"></script>
<script type="text/javascript" src="../../views/js/estructura/GenDinamico.js"></script>
<script type="text/javascript" src="../../views/js/estructura/gest_Puestos.js"></script>
<script type="text/javascript" src="../../views/js/estructura/gest_Medios.js"></script>
<script type="text/javascript" src="../../views/js/estructura/gestionarCargo.js"></script>
<script type="text/javascript" src="../../views/js/estructura/gest_Agrupacion.js"></script>
<script type="text/javascript" src="../../views/js/estructura/gestionarestructura.js"></script>


</body>
<div id="organigrama"></div>
</html>
