<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatComponenteCompuesto extends BaseDatComponenteCompuesto
{
    public function  setUp() {
        parent::setUp();
        $this->hasOne('NomTipoComponenteCompuesto', array('local'=>'idtipo_componente_compuesto','foreign'=>'idtipo_componente_compuesto'));
        $this->hasOne('DatSeleccionmultiple', array('local'=>'idcomponente_compuesto','foreign'=>'idcomponente_compuesto'));
        $this->hasOne('DatComboCompuesto', array('local'=>'idcomponente_compuesto','foreign'=>'idcomponente_compuesto'));        
    }
    
    public function obtenerComponentesCompuestos($idtabla)
    {
        $query = new Doctrine_Query();
        return $query->from('DatComponenteCompuesto cc')
                     ->where('cc.idtablamaster = ?',$idtabla)
                     ->setHydrationMode(Doctrine::HYDRATE_RECORD)
                     ->execute();
    }

}
