<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatComboCompuesto extends BaseDatComboCompuesto
{
    public function  setUp() {
        parent::setUp();
        $this->hasOne('DatComponenteCompuesto', array('local'=>'idcomponente_compuesto','foreign'=>'idcomponente_compuesto'));        
    }    

}
