<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatRemoto extends BaseDatRemoto
{
	public function setUp() 
    {   parent::setUp(); 
         $this->hasOne('DatRelacion as Origen', array('local'=>'campo_origen','foreign'=>'campo_origen')); 
         $this->hasOne('DatRelacion as Destino', array('local'=>'campo_destino','foreign'=>'campo_destino')); 
         $this->hasOne('DatCombo', array('local'=>'idcomponente','foreign'=>'idcomponente')); 

    } 

}
