<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gestionar Temas</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<!--<script language="javascript" type="text/javascript">importarCSS4(window.parent.UCID.portal.perfil.dirCss);</script>-->

<link rel="stylesheet" type="text/css" href="../../views/css/gestnomtema/gestnomtema.css" />
<link href="<?php echo $this->dir_ext_ccs;?>../gray4/css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
</head>

<body>
<div id="panel"></div>

<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all-4.2.1.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/4.2/BugFixed.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/components/class.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/desktop/FormDesktop.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/desktop/TabDesktop.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/presentacion/FormPresentacion.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/presentacion/TabPresentacion.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/comercial/FormComercial.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/comercial/TabComercial.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/Editor.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/autenticacion/FormAutenticacion.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/autenticacion/Autenticacion.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/AutenticacionEditor.js"></script>
<script type="text/javascript" src="../../views/js/gestnomtema/gestnomtema.js"></script>

</body>
</html>
