<html>
<head>
    <title>Gestionar Grupo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/imporcss.js"></script>
    <link href="<?php echo $this->dir_ext_ccs; ?>../default/css/ext-all.css" rel="stylesheet" type="text/css"
          media="screen"/>
    <link rel="stylesheet" type="text/css" href="../../views/css/css/TreeGrid.css"/>
    <link rel="stylesheet" type="text/css" href="../../views/css/css/iconcombo.css"/>
    <link rel="stylesheet" type="text/css" href="../../views/css/css/ScripDoc.css"/>


</head>
<body>
<div id="contenedor"></div>
<div id="ventana"></div>

<script type="text/javascript" src="<?php echo $this->dir_extjs; ?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs; ?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/eav/loadeavjs.php"></script>

</body>
</html>
