<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gestor Dinamico de Carpetas</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<link href="<?php echo $this->dir_ext_ccs; ?>../default/css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
<style type="text/css">
.search-item {
    
    padding:3px 10px 3px 10px;
    border:1px solid #555;
    border-top:1px solid #eeeeee;
    border-right:1px solid #eeeeee;
    white-space:normal;
   
}
.padding-expander{
         padding-top: 10px;
         padding-right: 0px;
         padding-bottom: 0px;
         padding-left: 20px;
} 
</style>
</head>

<body>
<div id="panel"></div>
<link rel="stylesheet" type="text/css" href="../../views/css/gestionarcarpetas/TreeGrid.css" />


<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>

<script type="text/javascript" src="../../views/js/gestionarcarpetas/RowExpander.js"></script>
<script type="text/javascript" src="../../views/js/gestionarcarpetas/gestionarcarpetas.js"></script>
</body>
</html>
