<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HisTraza extends BaseHisTraza
{
    function setUp()
    {
        $this->hasOne('NomTipotraza', array('local' => 'idtipotraza', 'foreign' => 'idtipotraza'));
    }

}
