<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NomTipotraza extends BaseNomTipotraza
{
    function setUp()
    {
        $this->hasMany('HiTraza', array('local' => 'idtipotraza',
            'foreign' => 'idtipotraza'));
    }

    static public function selectAlltipo()
    {
        $query = Doctrine_Query::create();
        return $query->select('t.idtipotraza, t.tipotraza')
            ->from('NomTipotraza t')
            ->execute()->toArray();
    }

    static public function cantidadTipos()
    {
        $query = Doctrine_Query::create();
        return $query->select('count (*) cantidad')
            ->from('NomTipotraza t');
        //->execute()->toArray();
    }

    static public function selectTipos($start, $limit)
    {
        $query = Doctrine_Query::create();
        return $query->select('t.idtipotraza, t.tipotraza')
            ->from('NomTipotraza t')
            ->limit($limit)
            ->offset($start)
            ->execute()->toArray();
    }

    static public function eliminarTraza($traza)
    {
        $query = Doctrine_Query::create();
        $query->delete()
            ->from('NomTipotraza t')
            ->where("t.idtipotraza = $traza")
            ->execute();
        return $traza;
    }


}

?>