Ext.define('GestNotas.model.Notas', {
    extend: 'Ext.data.Model',
    //USAR EL METODO setFields DEL MODEL PARA PONERLE CAMPOS DINAMICOS
    fields: [
        {name: 'idalumno', type: 'int'},
        {name: 'idpd', type: 'int'},
        {name: 'idmateria', type: 'int'},
        {name: 'codigo', type: 'string'},
        {name: 'facultad', type: 'string'},
        {name: 'codmateria', type: 'string'},
        {name: 'materia', type: 'string'},
        {name: 'nombre', type: 'string'},
        {name: 'apellidos', type: 'string'},
        {name: 'observaciones', type: 'string'},
        {name: 'nota1',  type: 'int'},
        {name: 'nota2',  type: 'int'},
        {name: 'nota3',  type: 'int'},
        {name: 'nota4',  type: 'int'},
        {name: 'nota5',  type: 'int'},
        {name: 'nota6',  type: 'int'},
        {name: 'nota7',  type: 'int'},
        {name: 'nota8',  type: 'int'},
        {name: 'nota9',  type: 'int'},
        {name: 'nota10',  type: 'int'},
        {name: 'nota11',  type: 'int'},
        {name: 'nota12',  type: 'int'},
        {name: 'nota13',  type: 'int'},
        {name: 'nota14',  type: 'int'},
        {name: 'nota15',  type: 'int'},
        {name: 'nota16',  type: 'int'},
        {name: 'nota17',  type: 'int'},
        {name: 'nota18',  type: 'int'},
        {name: 'nota19',  type: 'int'},
        {name: 'nota20',  type: 'int'}
    ]
}) 
