<html>
<head>
    <title>Generador de Interfaces</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/imporcss.js"></script>
    <link href="<?php echo $this->dir_ext_ccs; ?>../gray4/css/ext-all.css" rel="stylesheet" type="text/css"
          media="screen"/>
</head>
<body>
<link href="../../css/css/org.css" rel="stylesheet" type="text/css">
<link href="../../views/css/gestinterfaz/gestinterfaz.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->dir_extjs; ?>js/ext-all-4.2.1.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/gestinterfaz/gestinterfaz.js"></script>

</body>
<div id="odddrganigrama"></div>
</html>
