<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gestionar Nomenclador de Gestor</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
    <link href="<?php echo $this->dir_ext_ccs; ?>../default/css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
</head>

<body>
<div id="panel"></div>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/tomarimagenes/tomarimagenes.js"></script>
<script type="text/javascript" src="../../views/js/tomarimagenes/webcam.js"></script>
<script language="JavaScript">webcam.set_quality( 100 ); // JPEG quality (1 - 100)</script>


</body>
</html>
