<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatEstructura extends BaseDatEstructura
{

    function ExistenNoAsociadasDomain($result)
    {
        if ($result) {
            return 1;
        }
        return 0;

    }
    /*



    */


}
