<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Configurar Perfil"</title>
    <link rel="stylesheet" type="text/css" href="../../views/css/message.css"/>
    <script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/imporcss.js"></script>
    <link href="<?php echo $this->dir_ext_ccs; ?>css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
</head>

<body>
<div id="panel"></div>
<script type="text/javascript" src="<?php echo $this->dir_extjs; ?>js/ext-all-4.2.1.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid; ?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/gestionarconexion/gestionarconexion.js"></script>
<script type="text/javascript" src="../../views/js/gestionarconexion/AUIconexion.js"></script>
<script type="text/javascript" src="../../views/js/gestionarconexion/message.js"></script>

</body>
</html>
