Ext.define('GestFaltas.model.Faltas', {
    extend: 'Ext.data.Model',

    fields: [
        {name: 'idalumno', type: 'int'},
        {name: 'idpd', type: 'int'},
        {name: 'idmateria', type: 'int'},
        {name: 'codigo', type: 'string'},
        {name: 'facultad', type: 'string'},
        {name: 'codmateria', type: 'string'},
        {name: 'materia', type: 'string'},
        {name: 'nombre', type: 'string'},
        {name: 'apellidos', type: 'string'},
        {name: 'observaciones', type: 'string'},
        {name: 'sem1',  type: 'int'},
        {name: 'sem2',  type: 'int'},
        {name: 'sem3',  type: 'int'},
        {name: 'sem4',  type: 'int'},
        {name: 'sem5',  type: 'int'},
        {name: 'sem6',  type: 'int'},
        {name: 'sem7',  type: 'int'},
        {name: 'sem8',  type: 'int'},
        {name: 'sem9',  type: 'int'},
        {name: 'sem10',  type: 'int'},
        {name: 'sem11',  type: 'int'},
        {name: 'sem12',  type: 'int'},
        {name: 'sem13',  type: 'int'},
        {name: 'sem14',  type: 'int'},
        {name: 'sem15',  type: 'int'},
        {name: 'sem16',  type: 'int'},
        {name: 'sem17',  type: 'int'},
        {name: 'sem18',  type: 'int'},
        {name: 'sem19',  type: 'int'},
        {name: 'sem20',  type: 'int'}
    ]
});