<html>

<head>
    <meta charset="UTF-8"/>
    <title>Sistema de la Universidad Ecotec</title>
   

    
    
    <link href="views/css/index/entry.css" rel="stylesheet" type="text/css">
	<link href="views/css/index/bootstrap/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="views/css/index/bootstrap/bootstrap-responsive.css" rel="stylesheet" type="text/css">
    <link href="views/css/index/bootstrap/docs.css" rel="stylesheet" type="text/css">


</head>
<body>  
<div class="container text-center" style="text-align:center;">
<div class="container" style="text-align:center;margin-bottom:20px;">
	<img style="float:right;margin-left:20px;" src="views/images/index/saue-logo.png" title="{fullName}" width="300">
	<div class="entry-up back" style="float:right;margin-left:15px;display:none"><i></i></div>
	
 </div>
 <div class="container one page text-center root " style="display: none;width:60%">
	 
	
 </div>

 <div class="container other" style="text-align:center">


 </div>
 
  <div class="container" style="text-align:center;margin-top:50px;">
	<h4 class="muted " ><i class="icon-home" style="margin-right:10px;"></i>Estructuras <img style="margin-left:15px;" src="views/images/index/cargando2.gif" id="loading" width="30"></h4>
	
 </div>


<div class="container" style="text-align:center;margin-top:40px;">
	 
	<a id="btn-exit" class="btn btn-danger" style="margin-right:5px;"><img src="../../lib/ExtJS/temas/personal4/icons/salir.png"  style="margin-right:5px;">Salir</a>
	 <a id="btn-access" class="btn btn-success disabled" style="margin-right:5px;"><img src="../../lib/ExtJS/temas/personal4/icons/siguienteinactivo.png"  style="margin-right:5px;">Acceder al sistema</a>
	
 </div>
 </div>
<footer style="bottom: 15px;width:100%;height:80px;">
	
	
	
</footer>

<script type="text/javascript" src="views/js/index/jquery.js"></script>
<script type="text/javascript" src="views/js/index/bootstrap.js"></script>

<script type="text/javascript" src="views/js/index/index.js"></script>

</body>
</html>
