<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SegCompartimentacionusuario extends BaseSegCompartimentacionusuario
{

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SegUsuario', array('local' => 'idusuario', 'foreign' => 'idusuario'));
    }

    static public function eliminarUsuarioDominio($idusuario, $iddominio)
    {
        $query = Doctrine_Query::create();
        $query->delete()->from('SegCompartimentacionusuario')->where('idusuario =? and iddominio =?', array($idusuario, $iddominio))->execute();
        return;
    }

    static public function cargardominioUsuario($idusuario)
    {
        $query = Doctrine_Query::create();
        $datos = $query->select('iddominio')
            ->from('SegCompartimentacionusuario')
            ->where("idusuario = ?", $idusuario)
            ->setHydrationMode(Doctrine :: HYDRATE_ARRAY)
            ->execute();

        return $datos;
    }

    /*    static public function cargarUsuarioDominio($iddominio)
        {
            $query = Doctrine_Query::create();
            $datos = $query->select('idusuario')
                ->from('SegCompartimentacionusuario')
                ->where("iddominio = ?", $iddominio)
                ->setHydrationMode(Doctrine :: HYDRATE_ARRAY)
                ->execute();
            echo '<pre>';print_r($datos);die('uuu');
            return $datos;
        }*/

    //RENE. Tuve que usar esta forma porque con doctrine daba bateo a la hora de recuperar esta info.
    //el método de arriba comentareado es el original
    static public function cargarUsuarioDominio($iddominio)
    {
        $query = Doctrine_Query::create();
        $stmt = $query->getConnection()->prepare("
            SELECT segc.idusuario
            FROM mod_seguridad.seg_compartimentacionusuario segc
            WHERE segc.iddominio=$iddominio;");
        $stmt->execute();
        $result = $stmt->fetchAll(PDO::FETCH_ASSOC);
        return $result;
    }
}