Ext.define('GestComponentes.view.FormModOper', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formmodoper',
    frame: true,
    region: 'center',
    width: 425,
    height: 380,
    disabled: true,
    initComponent: function() {
        this.items = [{
                title: perfil.etiquetas.lbTitOperacion,
                frame: true,
                height: 450,
                items: [{frame: true, layout: 'column', items: [{
                                xtype: 'textfield',
                                width: 230,
                                fieldLabel: perfil.etiquetas.lbTitNombre,
                                name: 'nombreoperm',
                                allowBlank: false,
                                blankText: perfil.etiquetas.lbMsgBlank,
                                regex: /^([a-zA-ZáéíóúñüÑ]+[a-zA-ZáéíóúñüÑ\d ]*)+$/,
                                regexText: perfil.etiquetas.lbFLDatInc,
                            }, {xtype: 'combobox',
                                store: 'ComboTDServStore',
                                width: 240,
                                margin: '0 0 0 20',
                                fieldLabel: perfil.etiquetas.lbTitRetorno,
                                value: '',
                                name: 'retornom',
                                queryMode: 'local',
                                displayField: 'name',
                                valueField: 'TD',
                            }, {xtype: 'textareafield',
                                width: 450,
                                name: 'descripoper',
                                fieldLabel: perfil.etiquetas.lbTitDescripcion,
                                height: 50,
                            }, ]},
                    {frame: true,
                        title: perfil.etiquetas.lbTitParametros,
                        layout: 'column',
                        items: [{frame: true,
                                layout: 'column',
                                itemId: 'panelparm',
                                height: 195,
                                width: 250,
                                items: [{xtype: 'textfield',
                                        fieldLabel: perfil.etiquetas.lbTitParametro,
                                        width: 240,
                                        blankText: perfil.etiquetas.lbMsgBlank,
                                        name: 'nombreparm',
                                        regex: /^([a-zA-ZáéíóúñüÑ]+[a-zA-ZáéíóúñüÑ\d\.\-\_ ]@*)+$/,
                                        regexText: perfil.etiquetas.lbFLDatInc,
                                        allowBlank: false, },
                                    {xtype: 'combobox',
                                        fieldLabel: perfil.etiquetas.lbTitTipo,
                                        value: '',
                                        width: 240,
                                        //allowBlank: false,
                                        store: 'ComboTDServStore',
                                        queryMode: 'local',
                                        displayField: 'name',
                                        name: 'tipoparametrom',
                                        valueField: 'TD',
                                    },
                                    {xtype: 'textareafield',
                                        width: 240,
                                        name: 'descripcionm',
                                        fieldLabel: perfil.etiquetas.lbTitDescripcion,
                                        height: 95,
                                        value: '',
                                        anchor: '100%'},
                                    {xtype: 'button', text: perfil.etiquetas.lbBtnAnnadir,
                                        itemId: 'btnaddparm',
                                        icon: perfil.dirImg + 'adicionar.png',
                                        iconCls: 'btn',
                                        margin: '13 0 0 7',
                                    }, {xtype: 'button',
                                        text: perfil.etiquetas.lbBtnModificar,
                                        disabled: true,
                                        itemId: 'btnmodparm',
                                        icon: perfil.dirImg + 'modificar.png',
                                        iconCls: 'btn',
                                        margin: '13 0 0 7',
                                    }, {xtype: 'button',
                                        text: perfil.etiquetas.lbBtnEliminar,
                                        disabled: true,
                                        itemId: 'btndellparm',
                                        icon: perfil.dirImg + 'eliminar.png',
                                        iconCls: 'btn',
                                        margin: '13 0 0 7',
                                    }]},
                            {xtype: 'gridpanelparmm',
                            }, ]},
                    {xtype: 'button', text: perfil.etiquetas.lbBtnAceptar,
                        itemId: 'btnaceptoperm',
                        icon: perfil.dirImg + 'aceptar.png',
                        iconCls: 'btn',
                        margin: '7 0 0 335',
                    },
                    {xtype: 'button', text: perfil.etiquetas.lbBtnCancelar,
                        itemId: 'btncancoperm',
                        icon: perfil.dirImg + 'cancelar.png',
                        iconCls: 'btn',
                        margin: '7 0 0 20',
                    }], }];
        this.callParent();
    },
});
